language: node_js

node_js:
  - '7'

branches:
  only:
  - master
  - /^greenkeeper/.*$/

before_install: yarn global add greenkeeper-lockfile@1

install:
  - yarn --pure-lockfile

notifications:
  email:
    recipients:
      - liuderchi@gmail.com
    on_success: never
    on_failure: change

before_script: greenkeeper-lockfile-update

script: npm run test

after_script: greenkeeper-lockfile-upload
