language: node_js

node_js:
  - '7'

branches:
  only:
  - master
  - /^greenkeeper/.*$/

install:
  - yarn --pure-lockfile

notifications:
  email:
    recipients:
      - liuderchi@gmail.com
    on_success: never
    on_failure: change

script: npm run test
